[keyboard]
bindings = [
    { key = "Super", mods = "None", chars = "\u0002" }
]

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x808080"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xff0000"
white = "0xffffff"
yellow = "0xff0099"

[colors.normal]
black = "0x000000"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xff0000"
white = "0xd0d0d0"
yellow = "0xff0099"

[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[cursor]
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "Off"
shape = "Block"

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 7.0

[font.bold]
family = "monospace"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true 

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ''',│`|:"' ()[]{}<>	'''

[terminal.shell]
args = ["--login"]
program = "/bin/bash"

[window]
decorations = "full"
decorations_theme_variant = "dark"
dynamic_padding = false
dynamic_title = true
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 2
y = 2

[window.position]
x = 0
y = 0

[general]
live_config_reload = true
working_directory = "None"

[terminal]
